spring.application.name=restful-web-services

management.endpoints.web.exposure.include=*
spring.datasource.url = jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

#logging.level.org.springframework = debug

#spring.mvc.apiversion.use.path-segment=0
#spring.mvc.apiversion.use.query-parameter=version
#spring.mvc.apiversion.use.header=X-API-VERSION